
package FINANCIERA;

import com.mysql.jdbc.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.Locale;
import java.util.Date;

public class nuevo extends javax.swing.JFrame {
    public static final String URL = "jdbc:mysql://localhost/login_bd";
  public static final String USERNAME = "Corona";
  public static final String PASSWORD = "1234";
    
  PreparedStatement ps;
  ResultSet rs;
    public static Connection getConection(){
    Connection con = null;
    try{
    Class.forName("com.mysql.jdbc.Driver");
    con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);
    JOptionPane.showMessageDialog(null,"Conexion exitosa");
    
    }catch (Exception e){
    System.out.println(e);
    
    }
    return con;
    }
    void fechas (){
    DateFormat df = DateFormat.getDateInstance();
    Date FechaActual = new Date();
    cale.setDate(FechaActual);
    ca1.setText(df.format(FechaActual));
    ca2.setText(df.format(FechaActual));
    ca3.setText(df.format(FechaActual));
    }

    public void limpiarcaja(){
    nc.setText(null);
     ndc.setText(null);
      ac.setText(null);
       nomcre.setText(null);
        catcaja.setText(null);
          montomi.setText(null);
          numcontra.setText(null);
         montoauto.setText(null);
         montoeje.setText(null);
            catinv.setText(null);
              catsta.setText(null);
            montootor.setText(null);
          carte.setText(null);
          tipocar.setSelectedIndex(0);
         tipocre.setSelectedIndex(0);
            stascon.setSelectedIndex(0);
            castiga.setSelectedIndex(0);
            pequepro.setSelectedIndex(0);
                 fechas();       
    
    
    }
    public nuevo() {
        initComponents();
         this.setTitle("Nuevo Registro");
        this.setLocation(600, 200);
        fechas();
        txtid.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ndc = new javax.swing.JTextField();
        ac = new javax.swing.JTextField();
        nomcre = new javax.swing.JTextField();
        catcaja = new javax.swing.JTextField();
        catinv = new javax.swing.JTextField();
        catsta = new javax.swing.JTextField();
        montootor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        montomi = new javax.swing.JTextField();
        numcontra = new javax.swing.JTextField();
        montoauto = new javax.swing.JTextField();
        montoeje = new javax.swing.JTextField();
        carte = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        nc = new javax.swing.JTextField();
        BuSCAR = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        cale = new com.toedter.calendar.JDateChooser();
        ca1 = new javax.swing.JTextField();
        ca2 = new javax.swing.JTextField();
        ca3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        tipocre = new javax.swing.JComboBox<>();
        tipocar = new javax.swing.JComboBox<>();
        stascon = new javax.swing.JComboBox<>();
        castiga = new javax.swing.JComboBox<>();
        pequepro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Numero de cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setText("Actividad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setText("Numero de credito");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setText("Categoria de producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel6.setText("Tipo de credito");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel7.setText("Tipo de cartera");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel8.setText("Fecha de apertura");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel9.setText("Fecha de vencimiento");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel10.setText("Fecha de ministra");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel11.setText("Categoria de inversion");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jLabel12.setText("Status contable");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jLabel13.setText("Cat_status");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jLabel14.setText("Monto otorgado");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        ndc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndcActionPerformed(evt);
            }
        });
        getContentPane().add(ndc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 190, -1));
        getContentPane().add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, -1));
        getContentPane().add(nomcre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, -1));
        getContentPane().add(catcaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 190, -1));
        getContentPane().add(catinv, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 140, -1));
        getContentPane().add(catsta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 140, -1));
        getContentPane().add(montootor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 140, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 100, 60));

        jButton2.setText("Volver");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 80, 40));

        jLabel15.setText("Monto ministra");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel16.setText("Numero de contrato");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel17.setText("Monto auto");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel18.setText("Monto ejecutivo");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jLabel19.setText("Cartera");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel20.setText("Castigado");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        jLabel21.setText("pequeño productor");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, -1));

        montomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montomiActionPerformed(evt);
            }
        });
        getContentPane().add(montomi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 140, -1));

        numcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numcontraActionPerformed(evt);
            }
        });
        getContentPane().add(numcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 140, -1));
        getContentPane().add(montoauto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 140, -1));
        getContentPane().add(montoeje, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 140, -1));

        carte.setEditable(false);
        carte.setText("TRADICIONAL");
        carte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carteActionPerformed(evt);
            }
        });
        getContentPane().add(carte, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 130, -1));

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 100, 60));

        jLabel22.setText("Nuevo registro");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel23.setText("Nombre Completo");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(nc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 190, -1));

        BuSCAR.setText("Buscar");
        BuSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuSCARActionPerformed(evt);
            }
        });
        getContentPane().add(BuSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 100, 50));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 100, 50));
        getContentPane().add(cale, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 170, -1));
        getContentPane().add(ca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 110, -1));
        getContentPane().add(ca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 110, -1));
        getContentPane().add(ca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 110, -1));

        jLabel24.setText("Dia y Fecha de hoy");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        txtid.setText("  ");
        txtid.setEnabled(false);
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        tipocre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIMPLE", "REFACCIONARIO", "CREDITO SIMPLE", "CUENTA CORRIENTE", "HABILITACION O AVIO", "PRENDARIO" }));
        tipocre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipocreActionPerformed(evt);
            }
        });
        getContentPane().add(tipocre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        tipocar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AA", "BA" }));
        getContentPane().add(tipocar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        stascon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));
        getContentPane().add(stascon, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        castiga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N(NO)", "S(SI)" }));
        getContentPane().add(castiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, -1));

        pequepro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N(NO)", "S(SI)" }));
        getContentPane().add(pequepro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ndcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ndcActionPerformed

    private void montomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montomiActionPerformed

    private void numcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numcontraActionPerformed

    private void carteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
          if (nc.getText().equals("") || (ndc.getText().equals("")) || (ac.getText().equals(""))
           || (nomcre.getText().equals("")) || (catcaja.getText().equals("")) || (tipocre.getSelectedItem().toString().equals("")) || (tipocar.getSelectedItem().toString().equals("")) 
               || (montomi.getText().equals("")) || (numcontra.getText().equals("")) || (montoauto.getText().equals("")) || (montoeje.getText().equals("")) 
               || (ca1.toString().equals("")) || (ca2.toString().equals("")) || (ca3.toString().equals("")) || (catinv.getText().equals("")) || (stascon.getSelectedItem().toString().equals("")) 
               || (catsta.getText().equals("")) || (montootor.getText().equals(""))  || (carte.getText().equals("")) || (castiga.getSelectedItem().toString().equals("")) || (pequepro.getSelectedItem().toString().equals("")))   {
            
             JOptionPane.showMessageDialog(this, "debe llenar todo los campos");
        
           ndc.requestFocus();
        }else{
         
              Connection con=null;
        try {
            con = getConection();
            ps = con.prepareStatement("INSERT INTO campos (nc, ndc, ac, nomcre, catcaja, tipocre, tipocar, montomi, numcontra, montoauto, montoeje, catinv, stascon, catsta, montootor, carte, castiga, pequepro, ca1, ca2, ca3 ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1,nc.getText());
            ps.setString(2,ndc.getText());
            ps.setString(3,ac.getText());
            ps.setString(4,nomcre.getText());
            ps.setString(5,catcaja.getText());
            ps.setString(6,tipocre.getSelectedItem().toString());
            ps.setString(7,tipocar.getSelectedItem().toString());
            ps.setString(8,montomi.getText());
            ps.setString(9,numcontra.getText());
            ps.setString(10,montoauto.getText());
            ps.setString(11,montoeje.getText());
            ps.setString(12,catinv.getText());
            ps.setString(13,stascon.getSelectedItem().toString());
            ps.setString(14,catsta.getText());
            ps.setString(15,montootor.getText());
            ps.setString(16,carte.getText());
            ps.setString(17,castiga.getSelectedItem().toString());
            ps.setString(18,pequepro.getSelectedItem().toString());
            ps.setString(19,ca1.getText());
           ps.setString(20,ca2.getText());
            ps.setString(21,ca3.getText());
           int res = ps.executeUpdate();
            if(res >0){
          JOptionPane.showMessageDialog(null, "Registro guardado con Exito");  
          limpiarcaja();
            }else {
            JOptionPane.showMessageDialog(null, " ERROR no se guardo registro"); 
            limpiarcaja();
            } con.close();
        }catch(Exception e) {
        System.err.println(e);
     }
        
        
          }
          
        
        

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     frm_sistema Expedientes =new frm_sistema();
     Expedientes.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void BuSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuSCARActionPerformed

        Connection con=null;
        try {
            con = getConection();
            ps = con.prepareStatement("SELECT * FROM campos WHERE ndc = ? ");
            ps.setString(1,ndc.getText());
        rs= ps.executeQuery();
        
        if(rs.next()){
        txtid.setText(rs.getString("id"));
        nc.setText(rs.getString("nc"));
        ndc.setText(rs.getString("ndc"));
        ac.setText(rs.getString("ac"));
        nomcre.setText(rs.getString("nomcre"));
        catcaja.setText(rs.getString("catcaja"));
        tipocre.setSelectedItem(rs.getString("tipocre"));
        tipocar.setSelectedItem(rs.getString("tipocar"));
        montomi.setText(rs.getString("montomi"));
        numcontra.setText(rs.getString("numcontra"));
        montoauto.setText(rs.getString("montoauto"));
        montoeje.setText(rs.getString("montoeje"));
        catinv.setText(rs.getString("catinv"));
        stascon.setSelectedItem(rs.getString("stascon"));
        catsta.setText(rs.getString("catsta"));
        montootor.setText(rs.getString("montootor"));
        carte.setText(rs.getString("carte"));
        castiga.setSelectedItem(rs.getString("castiga"));
        pequepro.setSelectedItem(rs.getString("pequepro"));
        ca1.setText(rs.getString("ca1"));
        ca2.setText(rs.getString("ca2"));
        ca3.setText(rs.getString("ca3"));
        
        }else{
        JOptionPane.showMessageDialog(null,"No existe ese registro");
        }
            
        }catch(Exception e) {
        System.err.println(e);
     }
        
    }//GEN-LAST:event_BuSCARActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
Connection con=null;
        try {
            con = getConection();
            ps = con.prepareStatement("UPDATE  campos SET nc=?, ndc=?, ac=?, nomcre=?, catcaja=?, tipocre=?, tipocar=?, montomi=?, numcontra=?, montoauto=?, montoeje=?, catinv=?, stascon=?, catsta=?, montootor=?, carte=?, castiga=?, pequepro=?, ca1=?, ca2=? ,ca3=? WHERE id=?");
            ps.setString(1,nc.getText());
            ps.setString(2,ndc.getText());
            ps.setString(3,ac.getText());
            ps.setString(4,nomcre.getText());
            ps.setString(5,catcaja.getText());
            ps.setString(6,tipocre.getSelectedItem().toString());
            ps.setString(7,tipocar.getSelectedItem().toString());
            ps.setString(8,montomi.getText());
            ps.setString(9,numcontra.getText());
            ps.setString(10,montoauto.getText());
            ps.setString(11,montoeje.getText());
            ps.setString(12,catinv.getText());
            ps.setString(13,stascon.getSelectedItem().toString());
            ps.setString(14,catsta.getText());
            ps.setString(15,montootor.getText());
            ps.setString(16,carte.getText());
            ps.setString(17,castiga.getSelectedItem().toString());
            ps.setString(18,pequepro.getSelectedItem().toString());
            ps.setString(19,ca1.getText());
            ps.setString(20,ca2.getText());
            ps.setString(21,ca3.getText());
            ps.setString(22,txtid.getText());
       
           int res = ps.executeUpdate();
            if(res >0){
          JOptionPane.showMessageDialog(null, "Registro Modificado con Exito");  
          limpiarcaja();
            }else {
            JOptionPane.showMessageDialog(null, " ERROR no se Modifico registro"); 
            limpiarcaja();
            } con.close();
        }catch(Exception e) {
        System.err.println(e);
     }
        
        
        
    }//GEN-LAST:event_modificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
     
       Connection con=null;
        try {
            con = getConection();
            ps = con.prepareStatement("DELETE FROM campos WHERE ndc=? ");
            ps.setInt(1, Integer.parseInt(ndc.getText()));
       
         
           int res = ps.executeUpdate();
            if(res >0){
          JOptionPane.showMessageDialog(null, "Registro Eliminado con Exito");  
          limpiarcaja();
            }else {
            JOptionPane.showMessageDialog(null, " ERROR hubo un problema al Eliminar"); 
            limpiarcaja();
            } con.close();
        }catch(Exception e) {
        System.err.println(e);
     } 
        
        
        
        
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void tipocreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipocreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipocreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuSCAR;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField ac;
    private javax.swing.JTextField ca1;
    private javax.swing.JTextField ca2;
    private javax.swing.JTextField ca3;
    private com.toedter.calendar.JDateChooser cale;
    private javax.swing.JTextField carte;
    private javax.swing.JComboBox<String> castiga;
    private javax.swing.JTextField catcaja;
    private javax.swing.JTextField catinv;
    private javax.swing.JTextField catsta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField montoauto;
    private javax.swing.JTextField montoeje;
    private javax.swing.JTextField montomi;
    private javax.swing.JTextField montootor;
    private javax.swing.JTextField nc;
    private javax.swing.JTextField ndc;
    private javax.swing.JTextField nomcre;
    private javax.swing.JTextField numcontra;
    private javax.swing.JComboBox<String> pequepro;
    private javax.swing.JComboBox<String> stascon;
    private javax.swing.JComboBox<String> tipocar;
    private javax.swing.JComboBox<String> tipocre;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
